//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 04:05:56 PM CET 
//


package de.unigoettingen.sub.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 *  752
 * 
 * <p>Java class for hierarchicalGeographicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hierarchicalGeographicType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="territory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="county" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="island" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hierarchicalGeographicType", propOrder = {
    "elements"
})
public class HierarchicalGeographicType {

    @XmlElements({
        @XmlElement(name = "county", namespace = "http://www.loc.gov/mods/v3", type = County.class, required = false),
        @XmlElement(name = "territory", namespace = "http://www.loc.gov/mods/v3", type = Territory.class, required = false),
        @XmlElement(name = "country", namespace = "http://www.loc.gov/mods/v3", type = Country.class, required = false),
        @XmlElement(name = "continent", namespace = "http://www.loc.gov/mods/v3", type = Continent.class, required = false),
        @XmlElement(name = "area", namespace = "http://www.loc.gov/mods/v3", type = Area.class, required = false),
        @XmlElement(name = "island", namespace = "http://www.loc.gov/mods/v3", type = Island.class, required = false),
        @XmlElement(name = "region", namespace = "http://www.loc.gov/mods/v3", type = Region.class, required = false),
        @XmlElement(name = "city", namespace = "http://www.loc.gov/mods/v3", type = City.class, required = false),
        @XmlElement(name = "state", namespace = "http://www.loc.gov/mods/v3", type = State.class, required = false),
        @XmlElement(name = "province", namespace = "http://www.loc.gov/mods/v3", type = Province.class, required = false)
    })
    protected List<Object> elements;

    /**
     * Gets the value of the continentsAndCountriesAndProvinces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the continentsAndCountriesAndProvinces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContinentsAndCountriesAndProvinces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getElements() {
        if (elements == null) {
            elements = new ArrayList<Object>();
        }
        return this.elements;
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class County extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Territory extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Country extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Continent extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Area extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Island extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Region extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class City extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class State extends ValueType {
    }

    /**
     * Created by jpanzer on 24.02.14.
     */
    public static class Province extends ValueType {
    }
}
