//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 04:05:56 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/mods/v3",
        xmlns = {
                @XmlNs(namespaceURI = "http://www.loc.gov/METS/", prefix = "mets"),
                @XmlNs(namespaceURI = "http://www.loc.gov/mods/v3", prefix = "mods"),
                @XmlNs(namespaceURI = "http://gdz.sub.uni-goettingen.de/", prefix = "gdz"),
                @XmlNs(namespaceURI = "http://www.digizeitschriften.de/", prefix = "dz"),
                @XmlNs(namespaceURI = "http://dfg-viewer.de/", prefix = "dv"),
                @XmlNs(namespaceURI = "http://www.w3.org/1999/xlink", prefix = "xlink")

        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package de.unigoettingen.sub.jaxb;


import javax.xml.bind.annotation.XmlNs;